### ISSUE TITLE
Broken link to Contributor's Guide in README

### ISSUE THREAD

**Issue by leighawilliamson** [elyra-ai/community#17]
In the README, there is the following:

Contributing
If you are interested in contributing to Elyra then checkout the [Contributor's Guide](https://github.com/elyra-ai/community/blob/main/contributing.md)

Please note that attempting to take one's browser to the link (https://github.com/elyra-ai/community/blob/main/contributing.md) produces a 404 Error with message: "The 'elyra-ai/community' repository doesn't contain the 'contributing.md' path in 'main'. "

Sort of makes it hard to get started as an aspiring contributor...

**Comment by ptitzler** [comment]
Thanks for reporting!
